### ISSUE TITLE
Wir anstatt ich?

### ISSUE THREAD

**Issue by ff6347** [fabianmoronzirfas/ostfalia_db_2016_hausarbeiten#1]
Hi @Karina1988 wollen wir uns auf einen Schreibstil einigen? Ich bin aktuell von einem `wir` ausgegangen du benutzt gerade das `ich`. Welches nehmen wir? 

Ich bin für wir. :-)

**Comment by Karina1988** [comment]
Hey, wir können gerne "wir" nehmen :-P Hatte da bis jetzt noch nicht so
richtig drauf geachtet. Alles, was ich bis jetzt geschrieben hab, ist eh
noch völlig unkorrigiert und ich muss über alles nochmal drüber gehen.:)

2017-01-18 8:54 GMT+01:00 Fabian Morón Zirfas <notifications@github.com>:

**Comment by ff6347** [comment]
cool
