### ISSUE TITLE
Einleitendes Kapitel 3.1 Netflix 

### ISSUE THREAD

**Issue by ff6347** [fabianmoronzirfas/ostfalia_db_2016_hausarbeiten#5]
Es wäre cool wenn du noch ein einleitendes Kapitel zum Thema Netflix hättest. Gerade wird man so sehr da reingeworfen.  

Also kurz erläutern warum wir Netflix ausgewählt haben zum Thema Data Science

**Comment by Karina1988** [comment]
Ja, mache ich noch! Dann bekomme ich auch besser die letzen 300 Wörter voll :-)

**Comment by ff6347** [comment]
👍
